List available actions with integrated mockups
MediaComem/biopocket-mobile pull request #12
Opened 2018-09-06 12:32 UTC by Tazaf

> **DO NOT MERGE:**
> Merge PR #11 on `sprint-2-introducing-actions`, then change the base branch from `integrating-mockups` to `sprint-2-introducing-action` before reviewing.

Add a new component to display each action, named `bip-action-card`.
It will be reused when the dashboard and the suggested actions will be
implemented.
It will also be updated when action microdata (like cost, time, etc) will
be implemented.

Add basis navigation for each Action. Right now, a simple blank page
displaying the name of the Action is available. The next PR will implement
the complete page (based on the currently available Action's data).

Update test to add some for the new component and update existing ones.
Also update the e2e, although on a very tiny scale.

STORY: TG-52

2018-11-27 13:06 UTC, AlphaHydrae requested changes

2018-11-27 13:06 UTC, AlphaHydrae commented on docs/components/bip-action-card.md
> +This component displays a card containing action's information. The result should (currently) look like the following:
```suggestion
This component displays a card containing an action's information. The result should (currently) look like the following:
```

2018-11-27 13:06 UTC, AlphaHydrae commented on src/components/bip-action-card/bip-action-card.spec.ts
> +      expect(component).to.be.an.instanceOf(BipActionCardComponent);
If that's not already done in a future PR, it would be good to check that some of the action's data is actually displayed (e.g. the action's title).

2018-11-27 13:06 UTC, AlphaHydrae commented on src/components/bip-action-card/bip-action-card.ts
> +  actionPage: any;
Is this used? It doesn't look like it in this PR (the `actionPage` in the list is used).

2018-11-27 13:06 UTC, AlphaHydrae commented on src/pages/actions-list/actions-list.ts
> +        Print.debug(LOG_REF, response.data);
Avoid leaving debug logs.

What we might consider doing sometime is putting a permanent log in the HTTP interceptor that would automatically log all requests and responses.

If we have the time, we might even find a way to easily toggle a "debug mode" at runtime without changing the code (like a suspicious Pi symbol in the corner of the page... or a keyboard shortcut or touch gesture). By default, only normal/warning/error messages would be displayed; debug messages would only be logged in debug mode.

2018-11-27 14:39 UTC, Tazaf commented on src/components/bip-action-card/bip-action-card.spec.ts
> +      expect(component).to.be.an.instanceOf(BipActionCardComponent);
Working on it.

2018-11-27 14:39 UTC, Tazaf commented on src/pages/actions-list/actions-list.ts
> +        Print.debug(LOG_REF, response.data);
Yep. That a miss. Will remove.

2018-11-27 14:56 UTC, Tazaf commented on src/components/bip-action-card/bip-action-card.ts
> +  actionPage: any;
Well... removing it (and the constructor) doesn't fail any of the tests.
So... either it is indeed useless, or we didn't make enough tests ^^

2018-11-28 14:24 UTC, AlphaHydrae approved these changes

2018-11-28 14:25 UTC, AlphaHydrae commented
@Tazaf Any idea why that test fails? Is it related to the removed attribute?

2018-11-29 08:13 UTC, Tazaf commented
Erh... no.
I'm pretty sure I tested On My Machine® before pushing.
I'll redo them, then.

2018-12-14 12:39 UTC, Tazaf commented
OK, I relaunched the tests on my machine, and they break at the same spot. I'll fix it.

2018-12-15 10:05 UTC, merged